### ISSUE TITLE
Unclear behaviour when `Listing deployed systems`

### ISSUE THREAD

**Issue by SpeckiJ** [opengeospatial/ogcapi-connected-systems#30]
During implementation of the different endpoints for `deployments` the following issue came up:

Situation:

There are as far as i can see only two different ways to link a `system` to a `deployment`: 

1. When POSTing `deployments` via [Create new deployments](https://opengeospatial.github.io/ogcapi-connected-systems/redoc/?url=../api/part1/openapi/openapi-connectedsystems-1.yaml#tag/Deployments/paths/~1deployments/post) systems can be linked via `properties->members@link`. 
2. The systems can be added dynamically later via [Add systems to a deployment ](https://opengeospatial.github.io/ogcapi-connected-systems/redoc/?url=../api/part1/openapi/openapi-connectedsystems-1.yaml#tag/Deployments/paths/~1deployments~1%7BdeploymentId%7D~1systems/post), also accepting only links.

Both of those endpoints (only) allow for adding `systems` to a `deployment` loosely via link. As far as I understood this link can be either local or absolute, i.e. you can reference a different instance of the ogcapi-cs hosted on a different domain.

Problem:

When looking at the endpoint [List deployed systems](https://opengeospatial.github.io/ogcapi-connected-systems/redoc/?url=../api/part1/openapi/openapi-connectedsystems-1.yaml#tag/Deployments/paths/~1deployments~1%7BdeploymentId%7D~1systems/get), you can  retrieve systems by specifying a deployment in the url. But instead of the links that were specified during creation, full descriptions of the `systems` are returned. Where do those full descriptions come from?

Is this just an inconsistency in the OpenAPI spec (wrong schemata linked)? Or is the API supposed to resolve all the links (including to external APIs) when the `/deployments/<id>/systems` endpoint is queried?

**Comment by alexrobin** [comment]
@SpeckiJ Thanks for the excellent feedback. You are right that this is an inconsistency unless we require the server to resolve the links before presenting it back to the client.

I think we could either:
- Support both system objects or links in the response
- Allow only links in the response (which is consistent with the POST body)
- Keep it like it is and mandate that the server resolves the link (would only to check that the links are valid too)

What would you rather do?

**Comment by alexrobin** [comment]
I guess this is a general pattern when there are one-to-many associations and that these associations are across servers, so we need to think about it in the general case perhaps.

Other places where this can happen (according to the [latest draft](https://opengeospatial.github.io/ogcapi-connected-systems/api/part1/standard/23-001r0.html)) are:

- deployment -> systems
- deployment -> featuresOfInterest
- deployment -> datastreams
- deployment -> controlstreams

- system -> components (although I would not necessarily expect components to be hosted on a separate server)
- system -> samplingFeatures
- system -> deployments

- procedure -> systems

- samplingFeature -> relatedSamplingFeatures
- samplingFeature -> datastreams
- samplingFeature -> controlstreams

**Comment by autermann** [comment]
I think resolving systems to their actual descriptions will be awkward to implement. The URL doesn't necessarily references a SensorML description in a Connected Systems API, but also could just be a GeoJSON file hosted elsewhere. Retrieving it, checking it's type, validating it and possible translating it into SensorML is in my opinion to error prone to be mandated by the spec.

Also I see no benefit to inline the systems here, I think just referencing things by their canonical URL is enough. This would also be consistent with the `/deployments/{deploymentId}` representation that includes only links. `/deployments/{deploymentId}/systems` is in my opinion only an endpoint used for modifying the deployment, for getting the deployment's systems most implementers will just request the deployment directly.

**Comment by alexrobin** [comment]
@autermann Yes I agree with you. So I'll go with item 1. in my list.

**Comment by alexrobin** [comment]
@autermann @SpeckiJ I started documenting this but ran into some issues if we use only links.

The main problem is that links don't have IDs so there is no way to DELETE or UPDATE a link once you have added it with a POST. Of course, we could just add an ID property to the links but then I realized we need a nested resource anyway, because the SensorML model contains more than just a link. It uses the `DeployedSystem` object (see [schema](https://github.com/opengeospatial/ogcapi-connected-systems/blob/master/sensorml/schemas/json/DeployedSystem.json)).

So I decided to make the subcollection at `{api_root}/deployments/{id}/systems` a collection of `DeployedSystem` resources rather than just links. I started documenting this and we can review it tomorrow.

**Comment by alexrobin** [comment]
@autermann I have also tested an alternative approach that consists in using subdeployments instead of nested `DeployedSystems` resources.

I think there are several advantages:

1. No need to introduce a new resource type
2. Handles use cases of large missions that are composed of smaller parts 
4. Each subdeployment includes the full metadata, which is useful especially when using the SensorML format (one can attach different contact info, configuration etc, to each deployed system).

I can see many use cases for this:

- Several stations deployed along a river: there would be a top level deployment for the entire river, and a sub deployment for each station.
- A fleet of UAV deployed to inspect an area: The top level deployment describes the entire mission, and each flight is a subdeployment where we could identify the pilot, the exact flight plan, etc.
-  Military deployments with multiple units deployed in different parts of a larger areas, and targeting different objectives.
- Multiple runs of the same simulation/model grouped into a simulation campaign.
- etc.

We can discuss on Thursday

**Comment by alexrobin** [comment]
@autermann I am thinking that having `DeployedSystem` as a separate sub-resource is a little overkill since it's basically a bunch of links (at least in its simplest form). So I'm wondering if we should simply embed the list of deployed systems inside the Deployment resource itself and remove the subcollection at `deployments/{id}/systems`.

This should be enough to handle simple deployments with only a few deployed systems, and for more complex use cases with a large number of deployed systems, we can use sub-deployments.

This is what a deployment with embedded deployed systems would look like:

- [In GeoJSON](https://github.com/opengeospatial/ogcapi-connected-systems/blob/master/api/part1/openapi/examples/deployments/deployment-geojson-alt.json)

- [In SensorML](https://github.com/opengeospatial/ogcapi-connected-systems/blob/master/api/part1/openapi/examples/deployments/deployment-sml-alt.json)

Note that I have also aligned the design to what SOSA/SSN does, that is having a single platform per deployment. So there is no more need to have payloads in SensorML since once deployment = one platform with its payloads (or just a simple list of systems with no platform).

I think it's easy enough to create/update the whole resource at once if the number of systems stays reasonable. And I really think the concept of sub-deployment will be better when one needs to handle a lot more deployed systems since it allows to organize things better (e.g. group them by units, by common operator, etc.).

What do you think?

**Comment by alexrobin** [comment]
Discussed during 02/15 Telecon.
No objections to implement Deployments this way

**Comment by alexrobin** [comment]
Subdeployments have now been added to the spec and there is no separate resource for a `DeployedSystem`. Links to deployed systems are simply provided as part of the `Deployment` resource.
