### ISSUE TITLE
SWE-Common UnitOfMeasurement

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ogcapi-connected-systems#40]
SensorThings currently has name, symbol and definition.

Is the UOM in SWE-Common allowed to have both a UCUM Code (symbol) and a href (definition) at the same time? Given the `oneOf` I guess not.
Is that on purpose, or more a side-effect of wanting to require at least one of the two?

**Comment by alexrobin** [comment]
No, SWE Common `uom` object does not allow both UCUM code and href at the same time.

We consider the UCUM code as more than a symbol, but as the definition of the unit itself since it can be parsed unambiguously to the correct unit (and any combinations of units). The only reason why we support the href alternative is for units that cannot be modeled with UCUM. But it's one or the other.

We could add name and symbol to the `uom` object as well though. The symbol would be especially useful when the UCUM code does not match the well known symbol (e.g. °C is `Cel` in UCUM).

**Comment by hylkevds** [comment]
That makes sense, thanks.

I think just symbol is enough, since name should be already covered by the label property.

**Comment by alexrobin** [comment]
Yep, I didn't remember that I already added a label property.
I just pushed the change to the schema.

**Comment by KathiSchleidt** [comment]
@alexrobin question on use of UoM Vocabs, while I appreciate [UCUM](https://ucum.org/ucum), I do also like [QUDT](https://qudt.org/). Any chance of adding a definition link to support this?

**Comment by KathiSchleidt** [comment]
@alexrobin many thanks for the clarifications! So we'll stick to UCUM for UoM

Related bit, I noticed in the examples you pointed me to that the definition references an old version of the NASA SWEET ontology that no longer resolves. Maybe either port to the new site under [BioPortal](https://bioportal.bioontology.org/ontologies/SWEET), or alternatively, what do you think about the use of QUDT here? e.g. [velocity](https://qudt.org/vocab/quantitykind/Velocity) or [radiance](https://qudt.org/vocab/quantitykind/Radiance)

**Comment by alexrobin** [comment]
FYI, I added an [example](https://docs.ogc.org/DRAFTS/24-014.html#json_quantity_obj) in the spec showing the UoM by href variant.

I used a monetary unit as an example since this cannot be expressed using UCUM.
